## Introduction to Numpy Array
### import the numpy

In [3]:
import numpy as np    #imports the numpy so the numpy metheds can be used

### creating the array from numpy(One dimentional array)

In [4]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


#### Getting the specific elemnet from the 1-D array

In [5]:
print(arr[3])     #output 4

4


### Two Dimentional array

In [6]:
# import numpy as np

arr1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9],
               ])

print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Getting the specific element from the the 2-D array

In [7]:
print(arr1[1,2])     #output 4

6


the output will be the 6


arr1[1,2]
--> 1, represents the number of rows and,
 2, prepresents the number of columns

### 3-D Array

In [8]:
arr2 = np.array([[[1,2,3],[4,5,6]],        #reperersents the depth, width, and the height
                [[7,8,9],[10,11,12]]])
print(arr2)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


#### Getting specific element from the 3-D array

In [9]:
print(arr2[0,1,2])

6


the output will be the 6

arr[0,1,2] --> 0 represents the depth,
1 reprentsts the width
and 2 represents the height if the array

# Other method of the Numpy array

In [12]:
array = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(array.size)

9


#### Printing the the date typeof array

In [11]:
print(array.dtype)

int64


#### Printing the Dimentions of the Array

In [13]:
print(array.ndim)

2


### Reshaping the array

In [18]:
import numpy as np

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9],
                [11,12,13]])      #-->  2D array

reshaped = arr.reshape(6,2)    #--> 4 is number of rows and 3 is number of columns
print(reshaped)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 11]
 [12 13]]


### Flatttening the array

In [19]:
import numpy as np
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9],
                [11,12,13]]) 

Flattened = arr.flatten()
print(Flattened)

[ 1  2  3  4  5  6  7  8  9 11 12 13]


### 

In [20]:
import numpy as np
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9],
                [11,12,13]]) 
sumof = arr.sum()
print(sumof)

81
